### ISSUE TITLE
My Electric doesn't resize for mobile's

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/development#2]
The original 'My Electric' app shrunk to the width/height of the mobile viewport and gracefully reduced the amount of visible data accordingly, however this does not happen in this Development branch version - App>My Electric and users have to resize and drag the screen to view the data.  
Does the development branch 'My Electric' folder need to be updated with the files from the Master branch?  
Also, are there any plans to make 'My Solar' mobile friendly.  
Thanks for the great work.  
Paul

**Comment by TrystanLea** [comment]
Hello Paul,

Yes definetly intended to be resizeable, I've got most of this working again now locally, just need to finish one or two other parts to this, would also be great to make my solar mobile friendly.
Thanks

Trystan

**Comment by TrystanLea** [comment]
mysolar now resizes a lot better, its not perfect, the graph is still not fully using the space but its quite a bit better.
